### ISSUE TITLE
Help for installation of RNA detector.

### ISSUE THREAD

**Issue by lingni07** [alessandrolaferlita/RNAdetector#16]
Hi Alessandro,
I have some RNA seq data to be analyzed, so I am trying to install RNA detector on the computer, but there is a warning message,

Installing...
Validating configuration:
Creating directories...Ok!
Generating Auth Token...An error occurred: Unexpected token I in JSON at position 103

I have installed the docker desktop v 20.10.7 on the computer (windows10 pro 1909, AMD Ryzen9 3950X) and activated Windows Subsystem for Linux (WSL) 2.
Please give me some suggestions about my installation of RNA detector.
Thanks in advance!
 Tengfang

**Comment by alaimos** [comment]
Dear Tengfang,

Thanks for trying RNAdetector. 
I verified your report and found a bug that stops new users from installing the software in our docker backend.
I will correct the bug and issue a new backend version soon.
When the correction is online, I will let you know so you can proceed with the setup.

Best,
Salvatore.
