### ISSUE TITLE
circRNA analysis pipeline doesn't work

### ISSUE THREAD

**Issue by m-kouhsar** [alessandrolaferlita/RNAdetector#19]
Hi

I tried to use you software to extract circRNA expression from paired end RNA-Seq data (my OS is linux). I followed the steps in Circular RNA analysis but in final step when I press the "START ANALYSIS" button nothing happens! and the pipeline don't start and don't add to jobs!

**Comment by alaimos** [comment]
Can you send us more details of the analysis you are running? For example, screenshots of all the steps for the circ-RNA analysis filled with the parameters would be helpful to identify what is happening.

**Comment by m-kouhsar** [comment]
The screenshot of all process is attached. I tried to run CIRIquant algorithm on a pared end sample. The sample was downloaded from [CIRIquant home page](https://github.com/Kevinzjy/CIRIquant/releases/download/v0.2.0/test_data.tar.gz

![RNADetectror1](https://user-images.githubusercontent.com/59332098/129937844-5817de4e-99dd-4a71-970f-facb7b992aa9.png)
![RNADetectror2](https://user-images.githubusercontent.com/59332098/129937848-9b3275d5-7dd6-48fa-99e1-5755f0f7f572.png)
![RNADetectror3](https://user-images.githubusercontent.com/59332098/129937851-3379e216-399b-436f-a413-4d3f8ae4442d.png)
![RNADetectror4](https://user-images.githubusercontent.com/59332098/129937853-867924f9-10ee-4ebc-a10c-5d97012e70ff.png)
![RNADetectror5](https://user-images.githubusercontent.com/59332098/129937855-bff3ac70-001a-451d-bf1a-ba58baa84b9f.png)
).

**Comment by alaimos** [comment]
Thank you for the screenshots. Did you download only the hg19 genome?
In any case, I will look into the problem and let you know as soon as I have more details.

**Comment by m-kouhsar** [comment]
Yeah, I downloaded only the h19 genome.

**Comment by alaimos** [comment]
I just released a new update that should fix your problem.
Let me know if everything now works when you can download and install the patched version (version number is still 0.0.4).

Thanks.

**Comment by alaimos** [comment]
Closed since no other comments have been received.
